# Generated by Django 5.2.16 on 2026-08-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0004_boqitem_full_spreadsheet_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boq',
            name='site',
        ),
    ]
