# Generated by Django 5.2.16 on 2026-08-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0005_remove_boq_site'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boqitem',
            unique_together=set(),
        ),
    ]
