# Generated by Django 5.2.16 on 2026-08-07 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0002_siteprogresstask_boq_siteprogresstask_boq_item'),
        ('sites', '0003_site_town'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionDeviation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ncr_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('source', models.CharField(choices=[('AUTO', 'Auto-detected'), ('MANUAL', 'Manually raised')], default='MANUAL', max_length=10)),
                ('deviation_type', models.CharField(choices=[('QTY_OVERRUN', 'Quantity over plan'), ('QTY_UNDERRUN', 'Quantity under plan'), ('OTHER', 'Other (manual report)')], max_length=30)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor')], default='MINOR', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('HOD_REVIEW', 'HOD review'), ('DIR_REVIEW', 'Director review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONDITIONAL', 'Conditional approval'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('planned_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('variance_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('variance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField()),
                ('remarks', models.TextField(blank=True, default='')),
                ('evidence_document_ids', models.JSONField(blank=True, default=list)),
                ('linked_progress_ids', models.JSONField(blank=True, default=list)),
                ('blocks_fac', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations_approved', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations_raised', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='sites.site')),
                ('site_task', models.ForeignKey(blank=True, help_text='Optional — set when the deviation is about a specific task/BOQ item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations', to='progress.siteprogresstask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'status'], name='deviations__site_id_44df53_idx'), models.Index(fields=['deviation_type', 'severity'], name='deviations__deviati_40553f_idx')],
            },
        ),
    ]
