# Generated by Django 5.2.16 on 2026-08-08 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviations', '0001_initial'),
        ('provinces', '0005_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='NcrSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncr_sequences', to='provinces.province')),
            ],
            options={
                'unique_together': {('province', 'year')},
            },
        ),
    ]
